server:
  port: 8080


spring:
  application:
    name: keycloak-example

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/manager-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: HqSLYJHxFz3ZNoab90a9y3WVR8WA2dij
            scope:
              - openid
              - microprofile-jwt
              - view
              - edit
